# Generated by Django 5.1.2 on 2024-11-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('password', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('user_type', models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], max_length=10)),
                ('info', models.TextField(blank=True, null=True)),
                ('specialization', models.CharField(max_length=100, null=True)),
                ('clinic_details', models.TextField(blank=True, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('code_created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('password', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('user_type', models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], max_length=10)),
                ('info', models.TextField(blank=True, null=True)),
                ('specialization', models.CharField(max_length=100, null=True)),
                ('clinic_details', models.TextField(blank=True, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('code_created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User Account',
                'verbose_name_plural': 'User Accounts',
            },
        ),
    ]
