# Generated by Django 5.1.2 on 2024-10-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup_docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=3)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=6)),
                ('password', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('info', models.TextField()),
                ('specialization', models.CharField(max_length=100)),
                ('clinic_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Signup_patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=3)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=6)),
                ('password', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
