# Generated by Django 5.1.2 on 2024-10-25 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup_docs',
            new_name='Signup_doc',
        ),
        migrations.RenameModel(
            old_name='Signup_patients',
            new_name='Signup_patient',
        ),
    ]
