# Generated by Django 5.1.3 on 2025-02-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='request_sent',
            field=models.BooleanField(default=False),
        ),
    ]
