# Generated by Django 5.1.3 on 2025-03-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_request_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='request_sent',
        ),
    ]
