# Generated by Django 5.1.2 on 2024-10-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_signup_docs_signup_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_doc',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='signup_patient',
            name='age',
            field=models.IntegerField(),
        ),
    ]
