# Generated by Django 5.1.3 on 2025-03-15 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_request_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypost',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommunityPost',
        ),
    ]
