# Generated by Django 5.1.2 on 2024-10-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_signup_doc_age_alter_signup_patient_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup_doc',
            name='age',
        ),
        migrations.RemoveField(
            model_name='signup_patient',
            name='age',
        ),
        migrations.AddField(
            model_name='signup_doc',
            name='date_of_birth',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='signup_patient',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='signup_doc',
            name='clinic_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signup_doc',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='signup_doc',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signup_patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
    ]
