# Generated by Django 5.1.2 on 2024-10-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_otp_alter_signup_doc_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.AddField(
            model_name='signup_patient',
            name='code_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='signup_patient',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signup_patient',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
