# Generated by Django 5.1.7 on 2025-04-02 02:58

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='original_user_type',
            field=models.CharField(blank=True, choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_image',
            field=models.ImageField(blank=True, help_text='Upload your medical license or ID for verification', null=True, storage=account.models.DoctorVerificationStorage(), upload_to='doctor-verifications/', verbose_name='Doctor Verification Document'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
