# Generated by Django 5.1.2 on 2024-10-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_delete_otp_signup_patient_code_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_doc',
            name='code_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='signup_doc',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signup_doc',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
