# Generated by Django 5.1.2 on 2024-10-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_delete_signup_doc_delete_signup_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
