# Generated by Django 5.1.2 on 2024-10-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='clinic_details',
        ),
        migrations.RemoveField(
            model_name='user',
            name='info',
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialization',
        ),
    ]
