# Generated by Django 5.1.2 on 2024-10-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_user_clinic_details_remove_user_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clinic_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
