# Generated by Django 5.1.2 on 2024-10-27 17:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_clinic_details_user_info_user_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_created_at',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(auto_now_add=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(blank=True, default=False, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=6, null=True), size=None),
        ),
    ]
