# Generated by Django 5.1.7 on 2025-04-22 12:09

import detect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name': 'Diagnosis', 'verbose_name_plural': 'Diagnoses'},
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='status',
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=detect.models.DiagnosisImageStorage(), upload_to='diagnosis_images/'),
        ),
    ]
