# Generated by Django 5.1.7 on 2025-04-03 02:11

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=community.models.CommunityImageStorage(), upload_to='community_images/'),
        ),
    ]
